kwthon-2024/Team2_BE

src/main/java/com/kwhackathon/broom/common/util/CookieGenerator.java, src/main/java/com/kwhackathon/broom/common/util/JwtGenerator.java, src/main/java/com/kwhackathon/broom/common/util/JwtUtil.java
JWT 발급 역할 분리:
- 쿠키 생성 클래스 분리
- JWT 발급, 검증 역할 분리
=> refactor: JWT 발급 역할 분리

src/main/java/com/kwhackathon/broom/common/config/CorsMvcConfig.java, src/main/java/com/kwhackathon/broom/common/config/SecurityConfig.java, src/main/java/com/kwhackathon/broom/common/filter/JwtFilter.java, src/main/java/com/kwhackathon/broom/common/filter/LoginFilter.java, src/main/java/com/kwhackathon/broom/common/filter/LogoutFilter.java
refresh token전송 과정에 쿠키 적용:
- refresh token 전달을 쿠키로 변경
- 토큰 검증 과정 수정
- 쿠키 전달을 위한 allowedOrigin 설정
=> fix: refresh token전송 과정에 쿠키 적용

src/main/java/com/kwhackathon/broom/common/util/CookieGenerator.java, src/main/java/com/kwhackathon/broom/common/util/JwtGenerator.java, src/main/java/com/kwhackathon/broom/common/util/JwtUtil.java
토큰 발급, 쿠키 생성 로직 수정:
- 토큰 발급 시 토큰의 종류를 나타내는 클레임 삭제
- 쿠키 생성 메서드에 만료 시간 파라미터 추가
=> refactor: 토큰 발급, 쿠키 생성 로직 수정

src/main/java/com/kwhackathon/broom/board/controller/BoardController.java, src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/dto/BoardRequest.java, src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/entity/Board.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardService.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
엔티티 수정 메서드 구현:
- 게시물 정보 수정 메서드 구현
- 게시물의 인원 모집 상태 변경 메서드 구현
게시물 CRUD구현:
- 게시물 작성 기능 구현
- 게시물 카테고리별 전체 조회 기능 구현
- 게시물 상세 내용 조회 기능 구현
- 인원을 모집 중인 게시글만 조회하기 기능 구현
- 게시물 검색 기능 구현
- 게시물 수정 기능 구현
- 내가 작성한 게시물만 조회 기능 구현
- 게시물의 인원 모집 상태 변경 기능 구현
- 게시물 삭제 기능 구현
=> feat: 게시판 기능 구현

src/main/java/com/kwhackathon/broom/board/dto/BoardRequest.java, src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/entity/Board.java
날짜 반환 형식 변경 기능 구현:
- 게시물 작성일이 오늘과 같으면 시간만 반환
- 게시물 작성일이 같은 년도이고 날짜가 다르면 날짜만 반환
- 게시물 작성일이 다른 년도이면 연, 월, 일을 모두 반환
=> feat: 날짜 반환 형식 변경 기능 구현

src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/entity/Board.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
게시물 삭제 로직 수정 및 필드명 수정:
- 게시물 엔티티의 id -> boardId로 수정
- 게시물 삭제 시 사용자 유효성 검사 및 예외처리 추가
- 게시물 삭제 시 게시물 유효성 검사 및 예외처리 추가
=> refactor: 게시물 삭제 로직 수정 및 필드명 수정

src/main/java/com/kwhackathon/broom/bookmark/controller/BookmarkController.java, src/main/java/com/kwhackathon/broom/bookmark/controller/BookmarkControllerImpl.java, src/main/java/com/kwhackathon/broom/bookmark/dto/BookmarkRequest.java, src/main/java/com/kwhackathon/broom/bookmark/repository/BookmarkRepository.java, src/main/java/com/kwhackathon/broom/bookmark/service/BookmarkService.java, src/main/java/com/kwhackathon/broom/bookmark/service/BookmarkServiceImpl.java
북마크 CRUD 구현:
- 북마크 등록 기능 구현
- 북마크로 등록된 게시물 조회 기능 구현
- 북마크 해제 기능 구현
=> feat: 북마크 CRUD 구현

src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
응답 형식 수정:
- 게시물 정보 반환 시 속성별로 나누어 반환
- 게시물 정보, 게시물 내용, 작성자 정보 분리
=> refactor: 응답 형식 수정

src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/dto/BoardRequest.java, src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardService.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
validation 적용:
- board생성 dto에 입력 조건 적용
- service레이어에서 검증 실행 적용
=> feat: validation 적용

src/main/java/com/kwhackathon/broom/user/controller/UserController.java, src/main/java/com/kwhackathon/broom/user/controller/UserOperations.java, src/main/java/com/kwhackathon/broom/user/entity/User.java, src/main/java/com/kwhackathon/broom/user/service/UserService.java, src/main/java/com/kwhackathon/broom/user/util/MilitaryBranch.java
user도메인 validation 적용 및 변수명 변경:
- user 회원가입 로직의 validation적용
- militaryChaplain -> militaryBranch 변수명 변경
=> refactor: user도메인 validation 적용 및 변수명 변경

src/main/java/com/kwhackathon/broom/board/controller/BoardController.java, src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/entity/Board.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardService.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
모집중인 게시글 조회 기능 통합:
- 게시글 전체 조회 기능에 모집중인 게시글만 보기 기능 통합
- 게시글 검색 기능에 모집중인 게시글만 보기 기능 통합
=> feat: 모집중인 게시글 조회 기능 통합

src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
검색 메서드 수정:
- 제목으로 게시글 조회시 키워드를 포함하는 모든 결과를 반환하도록 수정
- 장소로 게시글 조회시 키워드를 포함하는 모든 결과를 반환하도록 수정
오타 수정:
- 컨트롤러의 예외메시지 오타 수정
=> fix: 검색 메서드 수정 및 오타 수정

src/main/java/com/kwhackathon/broom/board/controller/BoardController.java, src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/dto/BoardRequest.java, src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/entity/Board.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardService.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java, src/main/java/com/kwhackathon/broom/board/util/category/Category.java
게시판 기능 수정 및 최적화:
- 게시판 category 삭제
- 게시판 isFull 삭제
- 해당 게시판의 채팅 참여자 수 반환 기능 추가
- 게시글 조회 쿼리문 최적화
=> refactor(board): 게시판 기능 수정 및 최적화

src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java
채팅방에서 내보내기 기능 추가에 따른 기능 수정:
- 참여 중인 인원수에 추방당한 사용자의 수 제외
- 참여 중인 사용자에 대한 변수 타입 수정 int -> long
=> feat($board): 채팅방에서 내보내기 기능 추가에 따른 기능 수정

src/main/java/com/kwhackathon/broom/user/entity/User.java, src/main/java/com/kwhackathon/broom/user/service/UserService.java
유저 엔티티 연결 수정:
- 유저 도메인 양방양 연결 삭제 , 단방향 연결로 변경
- 회원가입 시 검증 로직 추가
=> refactor($user): 유저 엔티티 연결 수정

src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java
게시판 정보 반환 시 참여자 수 반환 과정 수정:
- 참여자 수에 게시글 작성자의 수 반영하지 않고 반환하도록 수정
=> fix($board): 게시판 정보 반환 시 참여자 수 반환 과정 수정

src/main/java/com/kwhackathon/broom/board/controller/BoardController.java, src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/dto/BoardResponse.java, src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardService.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java, src/main/java/com/kwhackathon/broom/common/config/SecurityConfig.java, src/main/java/com/kwhackathon/broom/user/controller/UserController.java, src/main/java/com/kwhackathon/broom/user/controller/UserOperations.java, src/main/java/com/kwhackathon/broom/user/dto/UserRequest.java, src/main/java/com/kwhackathon/broom/user/dto/UserResponse.java, src/main/java/com/kwhackathon/broom/user/repository/UserRepository.java, src/main/java/com/kwhackathon/broom/user/service/UserService.java, src/main/java/com/kwhackathon/broom/user/util/Role.java
관리자 기능 구현:
- role의 시큐리티 권한 적용을 위한 prefix 추가
- 관리자 접근 경로 설정 추가
- 서비스 현황의 총 유저 수 조회 기능 구현
- 서비스 현황의 총 게시글 수 조회 기능 구현
=> feat($admin): 관리자 기능 구현

src/main/java/com/kwhackathon/broom/date_tag/controller/DateTagController.java, src/main/java/com/kwhackathon/broom/date_tag/controller/DateTagControllerImpl.java, src/main/java/com/kwhackathon/broom/date_tag/dto/DateTagRequest.java, src/main/java/com/kwhackathon/broom/date_tag/dto/DateTagResponse.java, src/main/java/com/kwhackathon/broom/date_tag/entity/DateTag.java, src/main/java/com/kwhackathon/broom/date_tag/repository/DateTagRepository.java, src/main/java/com/kwhackathon/broom/date_tag/service/DateTagService.java, src/main/java/com/kwhackathon/broom/date_tag/service/DateTagServiceImpl.java
날짜 태그 기능 구현:
- 날짜 태그 CRUD 기능 구현
- 태그 생성, 수정, 삭제에 관리자 권한 확인 적용
- 반환 시 형식 변환 구현
=> feat($DateTag): 날짜 태그 기능 구현

src/main/java/com/kwhackathon/broom/board/repository/BoardRepository.java
인원수 카운트 버그 수정 및 미사용 기능 삭제:
- 채팅방 입장 시 참여 가능 여부 조회 과정에서의 인원수 카운트 오류 수정
- 동적 쿼리 적용에 따른 기존 조회, 검색 기능 삭제
=> fix($board): 인원수 카운트 버그 수정 및 미사용 기능 삭제

build.gradle, src/main/java/com/kwhackathon/broom/board/controller/BoardController.java, src/main/java/com/kwhackathon/broom/board/controller/BoardControllerImpl.java, src/main/java/com/kwhackathon/broom/board/repository/BoardSearchRepository.java, src/main/java/com/kwhackathon/broom/board/service/BoardService.java, src/main/java/com/kwhackathon/broom/board/service/BoardServiceImpl.java, src/main/java/com/kwhackathon/broom/common/config/QueryDslConfig.java
동적 쿼리 적용:
- 게시글 검색, 전체 조회 기능 통합
- queryDSL을 이용하여 동적 쿼리 적용
=> feat($Board): 동적 쿼리 적용

src/main/java/com/kwhackathon/broom/common/util/CookieGenerator.java
쿠키 설정 변경:
- 쿠키 생성시 samesite None 설정 추가
=> feat: 쿠키 설정 변경

src/main/java/com/kwhackathon/broom/bus/controller/BusReservationController.java, src/main/java/com/kwhackathon/broom/bus/controller/BusReservationOperators.java, src/main/java/com/kwhackathon/broom/bus/dto/BusResponse.java, src/main/java/com/kwhackathon/broom/bus/entity/BusReservationActivate.java, src/main/java/com/kwhackathon/broom/bus/repository/BusReservationActivateRepository.java, src/main/java/com/kwhackathon/broom/bus/service/BusReservationService.java
버스 신청 기능 온오프 기능 구현:
- 관리자에 의한 버스 신청 기능 활성화 상태 변경 기능 구현
=> feat($BusReservation): 버스 신청 기능 온오프 기능 구현

src/main/java/com/kwhackathon/broom/bus/dto/BusResponse.java, src/main/java/com/kwhackathon/broom/bus/service/BusReservationService.java
버스 신청 정보 확인 기능 수정:
- 버스 신청 정보 확인 시 신청자 정보가 아닌 신청 여부 boolean값 반환
=> fix($BusReservation): 버스 신청 정보 확인 기능 수정

src/main/java/com/kwhackathon/broom/user/entity/User.java
회원탈퇴 오류 해결:
- 사용자, 게시물, 북마크 간의 영속성 전이 추가
=> fix($User): 회원탈퇴 오류 해결
